### ISSUE TITLE
Types not loading correctly with the default installation instructions.

### ISSUE THREAD

**Issue by virtuallyunknown** [violentmonkey/types#5]
Hey.

I've noticed that using the default instructions provided don't really work. Example configuration:

```json
{
    "compilerOptions": {
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "target": "ESNext",

        "forceConsistentCasingInFileNames": true,
        "allowUnreachableCode": true,
        "noErrorTruncation": true,

        "esModuleInterop": true,
        "isolatedModules": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,

        "strict": true,
        "noEmit": false,
        "rootDir": "./src",
        "outDir": "./dist/"
    },
    "include": ["./src", "node_modules/@violentmonkey/types"],
    "exclude": ["**/node_modules", "**/.*/"]
}
```

With this configuration, all works fine inside `.js` files, I get intellisense, autocomplete and all of that. But I am getting type errors in `.ts` files. So I had to use the `types` property instead. With it, everything works correctly.

```json
{
    "compilerOptions": {
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "target": "ESNext",

        "forceConsistentCasingInFileNames": true,
        "allowUnreachableCode": true,
        "noErrorTruncation": true,

        "esModuleInterop": true,
        "isolatedModules": true,
        "resolveJsonModule": true,
        "skipLibCheck": true,

        "strict": true,
        "noEmit": false,
        "rootDir": "./src",
        "outDir": "./dist/",
        "types": ["@violentmonkey/types"]
    },
    "include": ["./src"],
    "exclude": ["**/node_modules", "**/.*/"]
}
```

**Comment by gera2ld** [comment]
The problem of the second way is that it prevents `@types/*` from being loaded automatically.

Perhaps it's because you excluded `node_modules` explicitly. Any reason why it's necessary?

**Comment by virtuallyunknown** [comment]
Hmm, I think it's pretty standard approach to exclude the node_modules directory, I basically do it for every project.

https://github.com/microsoft/TypeScript/wiki/Performance#specifying-files

But either way, this is less of a problem than just opening this issue in case someone else stumbles upon it in the future, just to have a workaround documented.

**Comment by gera2ld** [comment]
I can confirm it's caused by `exclude: ["**/node_modules"]`.
Maybe it's better to `import "@violentmonkey/types"` in a `shim.d.ts` file.
I'll update README. Thanks for reporting.

**Comment by virtuallyunknown** [comment]
No problem, thanks for developing Violentmonkey!
